[tool.poetry]
name = "extracting-sec-filings"
version = "0.1.0"
description = "scrape bulk sec filings"
authors = ["eo1989 <eorlowski6@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10.2"
pandas = "^1.4.3"
numpy = "^1.23.1"
beautifulsoup4 = "^4.11.1"
pyarrow = "^9.0.0"
fastparquet = "^0.8.1"
requests = "^2.28.1"
requests-random-user-agent = "^2022.6.25"
lxml = "^4.9.1"

[tool.poetry.dev-dependencies]
ipykernel = "^6.15.1"
jupytext = "^1.14.1"
nbformat = "^5.4.0"
flake8 = "^5.0.4"
yapf = "^0.32.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
